# Часть 1

## 4.1

Зададим матрицу B для расширенного кода Голея

In [1022]:
import numpy as np
B = np.array([[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
[1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
[0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
[1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
[1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
[1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
[0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
[0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
[0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
[1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
[0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

Построим порождающую матрицу

In [1023]:
G = np.hstack((np.eye(12, 12, dtype=int), B))
print(G)

[[1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 0 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0]]


Построим проверочную матрицу

In [1024]:
H = np.vstack((np.eye(12, 12, dtype=int), B))
print(H)

[[1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 0 1 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 0 0 0 1 0 1 1]
 [0 1 1 1 0 0 0 1 0 1 1 1]
 [1 1 1 0 0 0 1 0 1 1 0 1]
 [1 1 0 0 0 1 0 1 1 0 1 1]
 [1 0 0 0 1 0 1 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1 1 1 1]
 [0 0 1 0 1 1 0 1 1 1 0 1]
 [0 1 0 1 1 0 1 1 1 0 0 1]
 [1 0 1 1 0 1 1 1 0 0 0 1]
 [0 1 1 0 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 0]]


## 4.2

Напишем функцию для нахождения допущенной ошибки

In [1025]:
def get_error(w, H, B):
    s = w @ H % 2
    u1 = None
    if sum(s) <= 3:
        u1 = np.array(s)
        u1 = np.hstack((u1, np.zeros(len(s), dtype=int)))
    else:
        for i in range(len(B)):
            temp = (s + B[i]) % 2
            if sum(temp) <= 2:
                ei = np.zeros(len(s), dtype=int)
                ei[i] = 1
                u1 = np.hstack((temp, ei))
    if u1 is not None:
        u1
    else:
        sB = s @ B % 2
        if sum(sB) <= 3:
            u1 = np.hstack((np.zeros(len(s), dtype=int), sB))
        else:
            for i in range(len(B)):
                temp = (sB + B[i]) % 2
                if sum(temp) <= 2:
                    ei = np.zeros(len(s), dtype=int)
                    ei[i] = 1
                    u1 = np.hstack((ei, temp))
    return u1


Введем функцию для допущения ошибки и поиска этой самой ошибки при помощи get_error()

In [1026]:
import random
def gen_and_check_error(u, G, H, B, error_rate):
    print("Исходное сообщение:", u)
    w = u @ G % 2
    print("Отправленное сообщение", w)
    error = np.zeros(w.shape[0], dtype=int)
    error_indices = random.sample(range(w.shape[0]), error_rate)
    for index in error_indices:
        error[index] = 1
    print("Допущенная ошибка:", error)
    w = (w + error) % 2
    print("Сообщение с ошибкой", w)
    error = get_error(w, H, B)
    print("Вызываем get_error, получаем ошибку:", error)
    if error is None:
        print("Ошибка обнаружена, исправить невозможно!")
        return
    message = (w + error) % 2
    print("Исправленное отправленное сообщение:", message)
    w = u @ G % 2
    if (not np.array_equal(w, message)):
        print("Сообщение было декодировано с ошибкой!")

Отправляем сообщение (1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0). Допустим однократную ошибку

In [1027]:
u = np.array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0])
gen_and_check_error(u, G, H, B, 1)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 1 1 0 1 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Вызываем get_error, получаем ошибку: [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


Допустим двухкратную ошибку

In [1028]:
gen_and_check_error(u, G, H, B, 2)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 1 1 0 1]
Вызываем get_error, получаем ошибку: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


Допустим трехкратную ошибку

In [1029]:
gen_and_check_error(u, G, H, B, 3)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 1 1 1 1 0 1 0 0 1]
Вызываем get_error, получаем ошибку: [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0]
Исправленное отправленное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]


Допустим четырехкратную ошибку

In [1030]:
gen_and_check_error(u, G, H, B, 4)

Исходное сообщение: [1 0 0 1 1 0 0 0 1 0 1 0]
Отправленное сообщение [1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 1 0 1 0 0 1]
Допущенная ошибка: [0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 0 1]
Вызываем get_error, получаем ошибку: None
Ошибка обнаружена, исправить невозможно!


# Часть 2

## 4.3

Введем функцию для формирования порождающей матрица кода Рида-Маллера

In [1031]:
def reed_muller_generator_matrix(r: int, m: int) -> np.ndarray:
    # Базовый случай: r = 0 -> вектор из 1 длины 2^m
    if r == 0:
        return np.ones((1, 2**m), dtype=int)
    
    # Базовый случай: r = m -> G(m-1, m) и внизу вектор [0...01]
    if r == m:
        G_m_m_1_m = reed_muller_generator_matrix(m-1, m)
        bottom_row = np.zeros((1, 2**m), dtype=int)
        bottom_row[0, -1] = 1
        return np.vstack([G_m_m_1_m, bottom_row])
    
    # Рекурсивный случай: [[G(r, m-1), G(r, m-1)],[0, G(r-1, m-1)]]
    G_r_m_m_1 = reed_muller_generator_matrix(r, m-1)
    G_r_m_1_m_m_1 = reed_muller_generator_matrix(r-1, m-1)
    
    # Верхняя часть: G(r, m-1) дублируется
    top = np.hstack([G_r_m_m_1, G_r_m_m_1])
    
    # Нижняя часть: нули слева и G(r-1, m-1) справа
    bottom = np.hstack([np.zeros((G_r_m_1_m_m_1.shape[0], G_r_m_1_m_m_1.shape[1]), dtype=int), G_r_m_1_m_m_1])
    
    # Объединение верхней и нижней части
    return np.vstack([top, bottom])

## 4.4

Сформируем порождающую матрицу для RM(1, 3)

In [1032]:
G = reed_muller_generator_matrix(1, 3)
print(G)

[[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]


Введем функцию для произведения Кронекера

In [1033]:
def kronecker_product(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    # Получаем размеры матриц
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    
    # Инициализируем результирующую матрицу
    result = np.zeros((rows_A * rows_B, cols_A * cols_B), dtype=A.dtype)
    
    # Вычисляем произведение Кронекера
    for i in range(rows_A):
        for j in range(cols_A):
            result[i*rows_B:(i+1)*rows_B, j*cols_B:(j+1)*cols_B] = A[i, j] * B
    
    return result

Введем функцию для формирования H_m^i

In [1034]:
def H_matrix(H, m, i):
    matrix = np.eye(2 ** (m - i), dtype=int)
    matrix = kronecker_product(matrix, H)
    matrix = kronecker_product(matrix, np.eye(2 ** (i - 1)))
    return matrix

Введем функцию, которая допускает ошибку в отправленном сообщении и исправляет ее

In [1035]:
def gen_and_check_error_RM(u, G, error_rate, m):
    print("Исходное сообщение:", u)
    w = u @ G % 2
    print("Отправленное сообщение", w)
    error = np.zeros(w.shape[0], dtype=int)
    error_indices = random.sample(range(w.shape[0]), error_rate)
    for index in error_indices:
        error[index] = 1
    print("Допущенная ошибка:", error)
    w = (w + error) % 2
    print("Сообщение с ошибкой", w)
    for i in range(len(w)):
        if w[i] == 0:
            w[i] = -1
    w_array = []
    H = np.array([[1, 1], [1, -1]])
    w_array.append(w @ H_matrix(H, m, 1))
    for i in range(2, m + 1):
        w_array.append(w_array[-1] @ H_matrix(H, m, i))
    maximum = w_array[0][0]
    index = -1
    for i in range(len(w_array)):
        for j in range(len(w_array[i])):
            if abs(w_array[i][j]) > abs(maximum):
                index = j
                maximum = w_array[i][j]
    counter = 0
    for i in range(len(w_array)):
        for j in range(len(w_array[i])):
            if abs(w_array[i][j]) == abs(maximum):
                counter += 1
            if (counter > 1):
                print("Невозможно исправить ошибку!")
                return
    message = list(map(int, list(('{' + f'0:0{m}b' + '}').format(index))))
    if maximum > 0:
        message.append(1)
    else:
        message.append(0)
    print("Исправленное сообщение:", np.array(message[::-1]))
    if (not np.array_equal(u, message)):
        print("Сообщение было декодировано с ошибкой!")

Допустим однократную ошибку

In [1036]:
m = 3
u = np.array([1, 0, 0, 1])
gen_and_check_error_RM(u, G, 1, m)

Исходное сообщение: [1 0 0 1]
Отправленное сообщение [1 1 1 1 0 0 0 0]
Допущенная ошибка: [0 0 1 0 0 0 0 0]
Сообщение с ошибкой [1 1 0 1 0 0 0 0]
Исправленное сообщение: [1 0 0 1]


Допустим двухкратную ошибку

In [1037]:
gen_and_check_error_RM(u, G, 2, m)

Исходное сообщение: [1 0 0 1]
Отправленное сообщение [1 1 1 1 0 0 0 0]
Допущенная ошибка: [0 1 0 1 0 0 0 0]
Сообщение с ошибкой [1 0 1 0 0 0 0 0]
Невозможно исправить ошибку!


# 4.5

Сформируем порождающую матрицу для RM(1, 4)

In [1038]:
G = reed_muller_generator_matrix(1, 4)
print(G)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]


Допустим однократную ошибку

In [1039]:
m = 4
u = np.array([1, 0, 1, 0, 1])
gen_and_check_error_RM(u, G, 1, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


Допустим двухкратную ошибку

In [1040]:
gen_and_check_error_RM(u, G, 2, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
Сообщение с ошибкой [1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


Допустим трехкратную ошибку

In [1041]:
gen_and_check_error_RM(u, G, 3, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0]
Сообщение с ошибкой [1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 1]
Исправленное сообщение: [1 0 1 0 1]


Допустим четырехкратную ошибку

In [1042]:
gen_and_check_error_RM(u, G, 4, m)

Исходное сообщение: [1 0 1 0 1]
Отправленное сообщение [1 1 0 0 1 1 0 0 0 0 1 1 0 0 1 1]
Допущенная ошибка: [0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0]
Сообщение с ошибкой [1 1 1 0 1 1 0 1 0 1 1 1 0 0 0 1]
Невозможно исправить ошибку!
